Repository AY2324S1-CS2103T-T08-1/tp, pull requests merged in 2023-11, with the labels that each got.

#190 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/terminalcommand.png
Labels: documentation

#189 Update UserGuide for Doctor Command
  docs/UserGuide.md
  src/main/resources/images/view_doctor.jpg
Labels: documentation

#191 Update User Guide: Introduction
  docs/UserGuide.md
Labels: documentation

#236 Fix GUI related Bugs
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/AppointmentWindow.java
  src/main/java/seedu/address/ui/DoctorWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PatientWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: bug

#260 Fix bugs related to UG
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: bug, documentation
